Repository armada-ths/armada.nu, pull requests merged in 2020-11, with the labels that each got.

#520 Update Pages “forStudents”
  content/forStudents.md
Labels: netlify-cms/pending_publish

#522 Update News “armada-magazine”
  content/news/armada-magazine.md
Labels: netlify-cms/pending_review

#523 Update Pages “partners”
  content/partners.md
Labels: netlify-cms/pending_publish

#524 Update Pages “diversity”
  content/diversity.md
  src/layouts/DiversityPage/index.scss
Labels: netlify-cms/pending_review

#521 Create Pages “armada-competition”
  content/armada-competition.md
  content/forStudents.md
  content/homepage.md
  content/sustainability.md
  src/layouts/CompetitionPage/index.js
  src/layouts/CompetitionPage/index.scss
  src/templates/pageQuery.js
  static/assets/armada-competition-header.jpg
  static/assets/images/header-images/competition.jpg
  static/assets/images/header-images/home.jpg
  static/assets/images/header-images/sustainability.jpg
Labels: netlify-cms/draft

#510 Update Pages “about”
  content/about.md
Labels: netlify-cms/draft
